pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Architectury'
			url = 'https://maven.architectury.dev/'
		}
		maven {
			name = 'NeoForged'
			url = 'https://maven.neoforged.net/releases/'
		}
		maven {
			name = 'parchmentmc'
			url = "https://maven.parchmentmc.org"
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'blockout'

include('common', 'fabric', 'neoforge')
