modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"

[[mods]]
    modId = "blockout"
    version = "${version}"
    displayName = "Blockout"
    description = "Lockout bingo mod for Minecraft"

[[mixins]]
    config = "blockout.mixins.json"

[[dependencies.blockout]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.blockout]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "BOTH"
